const assert = require('assert')
const Rules = require('../../utils/game-rules')
const Records = require('../../utils/game-records')
const View = require('../../utils/round-view')
const Reports = require('../../utils/battle-report')
let def
const storage = {}
global.Page = value => { def = value }
global.wx = { getStorageSync: k => storage[k], setStorageSync: (k,v) => { storage[k] = Records.clone(v) }, removeStorageSync: k => { delete storage[k] }, showModal: o => o.success({confirm:true}), showToast() {}, navigateTo() {} }
require('../../pages/game/board')
const make = () => ({...def, data: Records.clone(def.data), setData(p) { Object.assign(this.data,p) }})
const board = make()
board.onLoad({config: JSON.stringify({gameType:'hanchan',rules:{bankruptcy:true,extension:false,dealerFinish:true},startPoints:25000,returnPoints:30000,uma:'10-20',players:['A','B','C','D']})})
assert.strictEqual(board.data.config.gameType,'free')
for (let n=0;n<32;n++) {
  assert.strictEqual(board.data.roundCycle,Math.floor(n/16)+1)
  assert.strictEqual(board.data.roundWind,Math.floor(n/4)%4)
  assert.strictEqual(board.data.roundNum,n%4+1)
  board.advanceRound(false,false)
  assert(!board.data.gameOver)
}
assert.strictEqual(board.data.roundCycle,3)
board.setData({roundCycle:1,roundWind:3,roundWindName:'北',roundNum:4,dealerIdx:3})
board.setData(Rules.nextRound(board.data,true,false))
assert.strictEqual(board.data.roundCycle,1)
assert.strictEqual(board.data.honba,1)
board.setData({selectedWinner:0,selectedLoser:1,inputPoints:'3900'})
board.confirmRon()
assert.strictEqual(board.data.roundCycle,2)
assert.strictEqual(board.data.roundWind,0)
assert.strictEqual(board.getRoundLabel(),'第2轮 · 東1局 0本场')
const resumed = make()
resumed.onLoad({resume:'1'})
assert.strictEqual(resumed.data.roundCycle,2)
resumed.undoLastRound()
assert.strictEqual(resumed.data.roundCycle,1)
assert.strictEqual(resumed.data.roundWind,3)
const label='第2轮 · 東1局 0本场'
assert.strictEqual(View.card({round:label}).roundTitle,'第2轮 · 東1局')
assert.strictEqual(View.card({round:label}).honbaLabel,'0本场')
const report=Reports.build({config:board.data.config,rounds:[{round:label,type:'ron',winner:'A',level:'满贯'}]})
assert.strictEqual(report.title,'对局战报')
assert.strictEqual(report.highlights[0].shortRound,'第2轮 · 東1局')
board.earlySettlement()
assert(board.data.gameOver)
assert.strictEqual(board.data.endReason,'手动结束')
console.log('Free play passed: 32-round rotation, dealer continuation, second-cycle labels, resume/undo, report and manual finish.')
